### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Fenyx4** [Gilmok/U4Rando#3]
Heya, would you mind putting a license on this? I hesitate to even look at it while working in my DOS Randomizer since you don't have a license.

Thanks.

**Comment by Gilmok** [comment]
What license do you suggest?  I know the MIT open source license is popular
for freeware such as this.

And you are free to look at the code (that's why I distributed it).

**Comment by Fenyx4** [comment]
I personally am a fan of the MIT License.

Thanks, I'll delve into it and might pinch a few of the flags for the DOS Randomizer. :)

**Comment by Gilmok** [comment]
I have added the license for software use to the main branch.
