### ISSUE TITLE
Shephard exp bug - bug or feature?

### ISSUE THREAD

**Issue by Gilmok** [Gilmok/U4Rando#7]
The shephard exp bug caused by the "wake up" function not being implemented properly (causes Shephard exp high byte to be ANDed with 0xFD at the end of each battle unless you have a full party).  While this is definitely an unintentional bug, there may be merit to leaving it in.  If you feel this is a BUG, I can simply fix it (the fix has already been programmed).  If you feel this is a FEATURE, I will need to go through the messy process of actually making it a flag.

**Comment by Fenyx4** [comment]
I guess it could be a good hard mode feature... But I don't think it would be one I'd ever use.

**Comment by Gilmok** [comment]
Version 1.7 fixes this bug.  Issue closed.
